version: 2
registries:
  maven-internal-releases:
    type: maven-repository
    url: https://nexus.cloudesire.com/repository/cloudesire-maven-snapshots/
    username: ${{secrets.NEXUS_MAVEN_USER}}
    password: ${{secrets.NEXUS_MAVEN_PASS}}
  maven-internal-snapshots:
    type: maven-repository
    url: https://nexus.cloudesire.com/repository/cloudesire-maven-releases/
    username: ${{secrets.NEXUS_MAVEN_USER}}
    password: ${{secrets.NEXUS_MAVEN_PASS}}
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
    registries:
      - maven-internal-releases
      - maven-internal-snapshots
    assignees:
      - malteo
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
    assignees:
      - malteo
