version: 2
registries:
  cloudesire-maven-group:
    type: maven-repository
    url: https://nexus.cloudesire.com/repository/cloudesire-maven-group/
    username: ${{secrets.NEXUS_MAVEN_USER}}
    password: ${{secrets.NEXUS_MAVEN_PASS}}
updates:
  - package-ecosystem: maven
    directory: "/"
    commit-message:
      prefix: "deps(maven)"
    schedule:
      interval: weekly
      day: sunday
    registries:
      - cloudesire-maven-group
    assignees:
      - malteo
  - package-ecosystem: docker
    directory: "/"
    commit-message:
      prefix: "deps(docker)"
    schedule:
      interval: weekly
      day: sunday
    assignees:
      - malteo
